name: automated-tests.

on:
  push:
    branches: [ master ]

env:
  PORT: ${{ secrets.PORT }}
  REDIS_URL: redis://localhost:6379

jobs:
  test_server:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Start Redis
      uses: supercharge/redis-github-action@1.7.0
      with:
        redis-version: '7'

    - name: Install dependencies and run tests
      run: |
        npm ci
        export PORT=$PORT
        export REDIS_URL=$REDIS_URL
        npm run ci-test

    - name: Test Failure
      if: failure()
      run: echo "Tests failed. Please check the logs for details."
